version: '3.8'

services:
  web:
    build:
      context: .
      target: web
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - agents

  agents:
    build:
      context: .
      target: agents
    ports:
      - "54367:54367"
    volumes:
      - .:/app
    env_file:
      - .env
